fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  resetting:
    email:
      template: '@FOSUser/Resetting/email.txt.twig'
      from_email:
        address: 'sow.mouctar@gmail.com'
        sender_name: 'ChangePassword'
  profile:
    form:
      type: App\Form\ProfileType

  registration:
    confirmation:
      template:   '@FOSUser/Registration/email.txt.twig'
    form:
      type: App\Form\RegistrationType

  from_email:
    address: '%env(resolve:USER_ADDRESS)%'
    sender_name: '%env(resolve:SENDER_NAME)%'

  service:
    mailer: 'fos_user.mailer.twig_swift'

framework:
  templating:
    engines: ['twig', 'php']

