parameters:
    locale: ~
    payment_log_dir: '%kernel.logs_dir%/payment/'
    voter_config: '%kernel.project_dir%/config/voters.yaml'
    app.path.users_images: /uploads/images/users
    csv_folder_path: '%kernel.project_dir%/var/import/db/'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventListener\JsVarsInitializeListener:
        arguments: ['@App\Service\JsVars', '%kernel.debug%']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    app.form.registration:
        class: App\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: App\Form\ProfileType
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@service_container'
        tags:
            - { name: form.type, alias: app_user_profile }

    App\Controller\ProfileController:
        arguments:
            - $formFactory: '@fos_user.profile.form.factory'

    App\Form\InstructorHourType:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@translator'

        # Event Subscribers
    App\EventListener\CustomRegistrationListener:
        arguments: ['@router', '@service_container']
        tags:
            - {name: kernel.event_subscriber}
    # Voters
    App\Security\ObjectVoter:
        arguments: ['%voter_config%']
        public: false
        tags:
            - { name: security.voter }

    App\Service\JsVars:
        public: true
        calls:
            - [enableTranslator, ['@translator']]
            - [enableRouter, ['@router']]
    App\Utils\DateHelper:
        arguments: ['@translator']
    App\Service\Import\ImportService:
        public: true

    App\Service\Import\FranceLocationImportService:
        public: true
        arguments:
            $filename: 'EUCircos_Regions_departements_circonscriptions_communes_gps.csv'